add introduction section for ISC'22 tutorial
easybuilders/easybuild-tutorial pull request #90
Opened 2022-05-18 06:05 UTC by boegel

2022-05-19 09:03 UTC, klust commented
Two links in the "Reproducilbility" subsection may need attention after assembling the tutorial. I assume the links with name "toolchain" and "easyconfig files" are meant to refer to sections in the terminology page?

2022-05-19 09:03 UTC, klust commented
Two links in the "Reproducilbility" subsection may need attention after assembling the tutorial. I assume the links with name "toolchain" and "easyconfig files" are meant to refer to sections in the terminology page?

2022-05-19 12:14 UTC, ocaisa requested changes
I think these should work

2022-05-19 12:14 UTC, ocaisa commented on docs/2022-isc22/introduction.md
> +Most software installations performed with EasyBuild use a **particular compiler <a href="#toolchains">toolchain</a>**,
```suggestion
Most software installations performed with EasyBuild use a **particular compiler [toolchain](terminology.md#toolchains)**,
```

2022-05-19 12:14 UTC, ocaisa commented on docs/2022-isc22/introduction.md
> +<a href="#easyconfig-files">easyconfig files</a>. That way, easyconfig files can easily be shared with others:
```suggestion
[easyconfig files](terminology.md#easyconfig-files). That way, easyconfig files can easily be shared with others:
```

2022-05-20 08:52 UTC, boegel commented on docs/2022-isc22/introduction.md
> +Most software installations performed with EasyBuild use a **particular compiler <a href="#toolchains">toolchain</a>**,
> I think these should work

@ocaisa Verified and fixed in 50d7f43

2022-05-20 09:04 UTC, ocaisa approved these changes

2022-05-20 09:04 UTC, merged