add installing software section for ISC'22 tutorial
easybuilders/easybuild-tutorial pull request #93
Opened 2022-05-18 13:00 UTC by SebastianAchilles

2022-05-19 10:07 UTC, klust requested changes

2022-05-19 10:07 UTC, klust commented on docs/2022-isc22/troubleshooting.md
> +grasping the solutions.
I wonder if we should add a warning that depending on how EasyBuild is used, a user may actually bump into T.2 before T.1? If you have the automatism to first check for dependencies, e.g., with eb -D, you'll actually first run in T.2, but if you just do `eb subread.eb` you'll run in T.1 first. Just a thought though, not a necessity.

2022-05-19 10:07 UTC, klust commented on docs/2022-isc22/troubleshooting.md
> +grasping the solutions.
I wonder if we should add a warning that depending on how EasyBuild is used, a user may actually bump into T.2 before T.1? If you have the automatism to first check for dependencies, e.g., with eb -D, you'll actually first run in T.2, but if you just do `eb subread.eb` you'll run in T.1 first. Just a thought though, not a necessity.

2022-05-19 10:07 UTC, klust commented on docs/2022-isc22/troubleshooting.md
> +    We don't have this GCC version installed, but we do have GCC 10.2.0:
This should be 11.2.0 here and in the next lines for the setup that we have for ISC'22.

2022-05-19 10:07 UTC, klust commented on docs/2022-isc22/troubleshooting.md
> +    We don't have this GCC version installed, but we do have GCC 10.2.0:
This should be 11.2.0 here and in the next lines for the setup that we have for ISC'22.

2022-05-19 10:07 UTC, klust commented on docs/2022-isc22/troubleshooting.md
> +In the end, you should be able to install Subread 2.0.1 with the GCC 10.2.0 toolchain by fixing the problems with the `subread.eb` easyconfig file.
with the GCC 11.2.0 toolchain instead of 10.2.0.

2022-05-19 10:07 UTC, klust commented on docs/2022-isc22/troubleshooting.md
> +In the end, you should be able to install Subread 2.0.1 with the GCC 10.2.0 toolchain by fixing the problems with the `subread.eb` easyconfig file.
with the GCC 11.2.0 toolchain instead of 10.2.0.

2022-05-19 13:37 UTC, SebastianAchilles commented on docs/2022-isc22/installing_software.md
> +  1) EasyBuild/4.4.5                7) XZ/5.2.5-GCCcore-11.2.0
Updated in https://github.com/easybuilders/easybuild-tutorial/pull/93/commits/d8546b1ba5bbbea229cb4b582998cc7bebddaa41

2022-05-19 13:37 UTC, SebastianAchilles commented on docs/2022-isc22/installing_software.md
> +The exercises are based on the easyconfig files included with EasyBuild 4.4.5.
Updated in https://github.com/easybuilders/easybuild-tutorial/pull/93/commits/d8546b1ba5bbbea229cb4b582998cc7bebddaa41

2022-05-19 13:46 UTC, ocaisa commented
@klust When you give this the ok I am happy to merge

2022-05-20 12:35 UTC, ocaisa commented
I'm going to merge this...

2022-05-20 12:35 UTC, ocaisa approved these changes

2022-05-20 12:37 UTC, ocaisa approved these changes

2022-05-20 12:38 UTC, merged